//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Razor_01_02_2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public int id { get; set; }
        public string Sender_Name { get; set; }
        public string Sender_Email { get; set; }
        public string Sender_Number { get; set; }
        public string Sender_Message { get; set; }
    }
}
