//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Razor_01_02_2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public int id { get; set; }
        public string project_name { get; set; }
        public string project_description { get; set; }
        public string project_img { get; set; }
    }
}
